### PR TITLE
Update tasklist_screen.dart

### PR DESCRIPTION
**Pull request by Laksh7218-git**
code for giving out the text well done the task is completed

### CODE REVIEW

**Comment by Smitbafna** [comment]
Update your PR with correct format

**Comment by Smitbafna** [comment]
@Laksh7218-git

**Comment by Laksh7218-git** [comment]
**Related Issue**
closes #36
**Type of change**
Put x inside the square bracket to specify what type of change your PR is:
New feature
**Description of change**
adding a function of void type
**Implementation**
I made a function of void type which includes the code which will pop up the message of well-done the task is completed with other characteristics too.

**Comment by pranavkonidena** [comment]
Please make sure to have a video demo to make it easy for the maintainers in issues which change some UI

**Comment by Akshit517** [comment]
@Laksh7218-git  There are merge conflicts. Please resolve them.

**Comment by pranavkonidena** [comment]
@Laksh7218-git Without a valid video demo by tomorrow EOD, we will have to allow other people to work on this issue!

**Comment by pranavkonidena** [comment]
@Laksh7218-git how did u make a PR then? I would assume u had the sim/device running the app to view your changes and verify they work..?

**Comment by pranavkonidena** [comment]
Btw any specific issues, u can post in the flutter channel on the img discord server.. people will help out there

**Comment by Laksh7218-git** [comment]
https://github.com/user-attachments/assets/d53fea3e-98ef-489e-917a-aacaa5244692

**Comment by Akshit517** [comment]
@Laksh7218-git We are closing this issue since this is not required implementation we wanted. Our intention was to use animation-related widgets to show task completion without relying on any packages.

**Pull request closed without merging**
